### ISSUE TITLE
Layout issue on a path

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#11]
On a path item, if someone posts content that extends past the associated map, the layout seems to break. It doesn't make sense to continue to the gray past the map, so is there a way to handle this? The main issue is that if someone posts an image to go with the map, any amount of content will probably extend past the gray border. https://gbof-web.netlify.app/paths/A-sample-journey#map=16/40.714349/-73.998742

<img width="1376" alt="Screenshot 2024-02-27 at 9 27 37 AM" src="https://github.com/performant-software/gbof-astro/assets/38816173/f527ad47-fb1b-490d-a1c1-5c8ff5729999">

**Comment by ajolipa** [comment]
See if the changes in PR #14 successfully address this; possibly more tweaking is needed but I think it's better at least.

**Comment by absempere** [comment]
Agreed -- can use some tweaking, but definitely better!
