### ISSUE TITLE
Add a "Back to Beginning" link for Paths

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#15]
Currently, once a user begins a Path, it's possible to step forward and backwards between Places, but the only way to return to the overview page is through the navigation at the top (clicking Paths and then finding and clicking the correct Path). It'd be helpful to have a way to return to a Path overview from within a Path, especially once we add an interactive map to the overview.

**Comment by ajolipa** [comment]
Addressed in PR #16 .

**Comment by absempere** [comment]
Works as a placeholder until we implement Chelsea's designs -- thanks.
