### ISSUE TITLE
Apply Post/Path styling to other pages

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#24]
It's currently impossible to see links from text on the front page of [GBoF production](https://gbof-web.netlify.app/ ). 

The project description has a link in it, but you can't see it unless you happen to hover over the phrase and see the cursor change.

**Comment by jamiefolsom** [comment]
I think links on the home page now show as **[bold and underlined](#)** (but not blue). If that's what's indicated in the design, would you confirm and close, @absempere?

**Comment by absempere** [comment]
There were no examples of URLs in the original design (all lorem ipsum placeholders), but Chelsea said this is fine!
