### ISSUE TITLE
Every time the Zoom button is clicked, the place name pops up

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#30]
One small UX thing: when I zoom in and out of the map, every time I click + or -, the place name pops up, so if I want to zoom out 2x, I have to click the button 4x. https://gbof-web.netlify.app/posts/Spanish-Language-Publication-Archives#map=12.85/40.7548/-73.9898

**Comment by jamiefolsom** [comment]
This appears to be treating the whole map as the click target, including the zoom buttons.

**Comment by ajolipa** [comment]
Fixed in PR #40

**Comment by absempere** [comment]
Seems to be working across the site -- thx!
