### ISSUE TITLE
Typing a search with no results crashes the map view

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/gbof-astro#32]
Pasting this link correctly shows a search with 0 results: 

[https://gbof-web.netlify.app/map?q=asdf#/&map=12.99/40.73215/-73.98924](https://gbof-web.netlify.app/map?q=asdf#/&map=12.99/40.73215/-73.98924)

However, going to: [https://gbof-web.netlify.app/map](https://gbof-web.netlify.app/map) typing "asdf" into the search field crashes the map.

Refer to Atlas [https://atlas-project-web.netlify.app/en/?q=asdf#/&map=1/0/0)](https://atlas-project-web.netlify.app/en/?q=asdf#/&map=1/0/0), which does not have this bug (both typing and pasting work).

**Comment by ajolipa** [comment]
Fixed in PR #40
