### ISSUE TITLE
GBoF course site cleanup

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#57]
- [ ] Remove About pages from C19 and Hudson Valley
- [ ] Update C19 and Hurricane Sandy to remove hardcoding of hero and feature images

**Comment by ajolipa** [comment]
Done. (Note C19 and Hurricane Sandy need images filled in on Tina now.)

**Comment by absempere** [comment]
I tried updating the C19 and Hurricane Sandy images, and they aren't going through....
