### ISSUE TITLE
Place Data isn't fully loading in TinaCMS Posts & Paths

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#6]
Currently we can only add a small subset of Places in Core Data to Posts or Paths. When creating a Post or Path with embedded Place Data:

- the Place Data dropdown lists about 10 places from Core Data instead of the ~155 possible places in GBoF
- it also isn't possible to type a place to find matches in Core Data

Could we add a way to populate the Place Data dropdown with matches to whatever to user is searching for?

**Comment by absempere** [comment]
@ajolipa A follow-up -- I can search and find places; however, once I select a place, the text field goes blank. At first I thought the place data hadn't loaded or saved, but when I checked the actual path, the info was there. 

Is it possible to keep the text in the field or to somehow indicate which Place Data is being used? These are two different stops on a path. Unless I remember which stop I'm editing or have a descriptive blurb, I can't tell where I am. 

<img width="1298" alt="Screenshot 2024-02-27 at 8 57 18 AM" src="https://github.com/performant-software/gbof-astro/assets/38816173/0a81c453-23b8-4d8c-b976-8e0546203b8e">

<img width="1305" alt="Screenshot 2024-02-27 at 8 57 43 AM" src="https://github.com/performant-software/gbof-astro/assets/38816173/54235669-5780-45bd-ba93-0fda0ce6e370">

**Comment by ajolipa** [comment]
This should now be fixed (as of merging PR #12 ).

**Comment by absempere** [comment]
Yes -- this is great. Thanks!
