### ISSUE TITLE
UX: Let's give links a different visual treatment

### ISSUE THREAD

**Issue by absempere** [performant-software/gbof-astro#9]
It's currently impossible to see the difference between regular text and links. In this path, "a sample post" is a link to a post on the GBoF site. Can we visually indicate that this is a link?

<img width="1303" alt="Screenshot 2024-02-27 at 9 02 56 AM" src="https://github.com/performant-software/gbof-astro/assets/38816173/5951777a-f540-481c-9c97-a2c927b4a117">

**Comment by ajolipa** [comment]
Addressed in PR #13 (and note that I haven't yet added custom styles, but the appearance of links and other textual elements within the markdown content can be further customized as needed).

**Comment by absempere** [comment]
This is already helpful -- at this point we want to demo what's possible, and this shows how they might use the site and connect various assignments/projects.
